### ISSUE TITLE
how to add bootstrap classes to inputs and labels

### ISSUE THREAD

**Issue by vladejs** [vazco/uniforms#39]
I am working on a bootstrap themed version of a site, so i want to specify classes to inputs like this:
```
<input className="button button-primary" />
```

Can I do thath from schema specification? Something like:
```
Person = new SimpleSchema
  submitButton:
    uniforms:
        classNames: "button button-primary"
```

The issue is, I want to use bootstrap 3 structure, but with different classes
